// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcjevH8LIhoKLeD_XrQNktkT4ASPDtDCs',
    appId: '1:527678259554:web:d1a84114336997098a2c3b',
    messagingSenderId: '527678259554',
    projectId: 'gestion-courses-cec47',
    authDomain: 'gestion-courses-cec47.firebaseapp.com',
    storageBucket: 'gestion-courses-cec47.firebasestorage.app',
    measurementId: 'G-S3W33MNG0Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjhoRJsGrrBp8t_IZgke0OfhFKyy5s_fc',
    appId: '1:527678259554:android:d8f423219502808e8a2c3b',
    messagingSenderId: '527678259554',
    projectId: 'gestion-courses-cec47',
    storageBucket: 'gestion-courses-cec47.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbacDWl5GDnaA8y4l7oou3Y--3Uiu0gac',
    appId: '1:527678259554:ios:3b88cbc30f0d03728a2c3b',
    messagingSenderId: '527678259554',
    projectId: 'gestion-courses-cec47',
    storageBucket: 'gestion-courses-cec47.firebasestorage.app',
    iosBundleId: 'com.example.gestionCourses',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbacDWl5GDnaA8y4l7oou3Y--3Uiu0gac',
    appId: '1:527678259554:ios:3b88cbc30f0d03728a2c3b',
    messagingSenderId: '527678259554',
    projectId: 'gestion-courses-cec47',
    storageBucket: 'gestion-courses-cec47.firebasestorage.app',
    iosBundleId: 'com.example.gestionCourses',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcjevH8LIhoKLeD_XrQNktkT4ASPDtDCs',
    appId: '1:527678259554:web:bf371f27f29904998a2c3b',
    messagingSenderId: '527678259554',
    projectId: 'gestion-courses-cec47',
    authDomain: 'gestion-courses-cec47.firebaseapp.com',
    storageBucket: 'gestion-courses-cec47.firebasestorage.app',
    measurementId: 'G-L16WQ35V6K',
  );
}