// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEfKfP_3Ix_NhHy7p9GBWaYK88MX3JQbc',
    appId: '1:96620784906:web:290c0491c93d1637e59ef3',
    messagingSenderId: '96620784906',
    projectId: 'gestion-courses-403c0',
    authDomain: 'gestion-courses-403c0.firebaseapp.com',
    storageBucket: 'gestion-courses-403c0.firebasestorage.app',
    measurementId: 'G-WRJMFFP539',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJplFV5sq20tT7838YWorZmJDWFn1J2jM',
    appId: '1:96620784906:android:31e0675c7d846844e59ef3',
    messagingSenderId: '96620784906',
    projectId: 'gestion-courses-403c0',
    storageBucket: 'gestion-courses-403c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWUFAudGpedjiJ8US96Zh1dPyixEmY7QY',
    appId: '1:96620784906:ios:950c573acd413edbe59ef3',
    messagingSenderId: '96620784906',
    projectId: 'gestion-courses-403c0',
    storageBucket: 'gestion-courses-403c0.firebasestorage.app',
    iosBundleId: 'com.example.gestionCourses',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWUFAudGpedjiJ8US96Zh1dPyixEmY7QY',
    appId: '1:96620784906:ios:950c573acd413edbe59ef3',
    messagingSenderId: '96620784906',
    projectId: 'gestion-courses-403c0',
    storageBucket: 'gestion-courses-403c0.firebasestorage.app',
    iosBundleId: 'com.example.gestionCourses',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEfKfP_3Ix_NhHy7p9GBWaYK88MX3JQbc',
    appId: '1:96620784906:web:ca92aab5146e94bee59ef3',
    messagingSenderId: '96620784906',
    projectId: 'gestion-courses-403c0',
    authDomain: 'gestion-courses-403c0.firebaseapp.com',
    storageBucket: 'gestion-courses-403c0.firebasestorage.app',
    measurementId: 'G-45839M67HY',
  );

}